[features]
seeds = false
skip-lint = false

[programs.localnet]
cat_coin_contracts = "CATCoinMainProgram1111111111111111111111111"

[programs.devnet]
cat_coin_contracts = "CATCoinMainProgram1111111111111111111111111"

[programs.mainnet]
cat_coin_contracts = "CATCoinMainProgram1111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000